<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="techtrix_robot">

  <xacro:include filename="$(find techtrix_description)/urdf/macros.xacro"/>
  <xacro:include filename="$(find techtrix_description)/urdf/techtrix_properties.xacro"/>
  <xacro:include filename="$(find techtrix_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find techtrix_description)/urdf/gazebo_plugins.xacro"/>

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <link name="frame">
    <!-- <collision>
      <geometry>
        <box size="${width} ${length} ${height}" />
      </geometry>
    </collision> -->
    <visual>
      <origin xyz="0 0.375 -2.355" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://techtrix_description/meshes/techtrix_frame.dae" scale="${1/3} ${1/3} ${1/3}" />
      </geometry>
    </visual>
    <xacro:default_inertial mass="1"/>
  </link>

  <link name="bearing">
    <xacro:default_inertial mass="1"/>
  </link>

  <link name="grabbing_mechanism_sc_1_laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>
  </link>
  <joint name="grabbing_mechanism_sc_1_laser_joint" type="fixed">
    <origin xyz="0.551 0 0" rpy="0 ${pi/2} 0" />
    <parent link="grabbing_mechanism"/>
    <child link="grabbing_mechanism_sc_1_laser" />
  </joint>

  <link name="grabbing_mechanism_sc_2_laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>
  </link>
  <joint name="grabbing_mechanism_sc_2_laser_joint" type="fixed">
    <origin xyz="0.339 0 0" rpy="0 ${pi/2} 0" />
    <parent link="grabbing_mechanism"/>
    <child link="grabbing_mechanism_sc_2_laser" />
  </joint>

  <link name="grabbing_mechanism_sc_3_laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>
  </link>
  <joint name="grabbing_mechanism_sc_3_laser_joint" type="fixed">
    <origin xyz="0.127 0 0" rpy="0 ${pi/2} 0" />
    <parent link="grabbing_mechanism"/>
    <child link="grabbing_mechanism_sc_3_laser" />
  </joint>

  <link name="grabbing_mechanism_sc_4_laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>
  </link>
  <joint name="grabbing_mechanism_sc_4_laser_joint" type="fixed">
    <origin xyz="-0.127 0 0" rpy="0 ${pi/2} 0" />
    <parent link="grabbing_mechanism"/>
    <child link="grabbing_mechanism_sc_4_laser" />
  </joint>

  <link name="grabbing_mechanism_sc_5_laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>
  </link>
  <joint name="grabbing_mechanism_sc_5_laser_joint" type="fixed">
    <origin xyz="-0.339 0 0" rpy="0 ${pi/2} 0" />
    <parent link="grabbing_mechanism"/>
    <child link="grabbing_mechanism_sc_5_laser" />
  </joint>

  <link name="grabbing_mechanism_sc_6_laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </visual>
  </link>
  <joint name="grabbing_mechanism_sc_6_laser_joint" type="fixed">
    <origin xyz="-0.551 0 0" rpy="0 ${pi/2} 0" />
    <parent link="grabbing_mechanism"/>
    <child link="grabbing_mechanism_sc_6_laser" />
  </joint>

  <link name="grabbing_mechanism">
    <collision name="grabbing_mechanism_sc_1_top">  
      <origin xyz="0.551 -0.098 -0.135" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_1_bot">  
      <origin xyz="0.551 -0.098 -0.255" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_2_top">  
      <origin xyz="0.339 -0.098 -0.135" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_2_bot">  
      <origin xyz="0.339 -0.098 -0.255" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_3_top">  
      <origin xyz="0.127 -0.098 -0.135" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_3_bot">  
      <origin xyz="0.127 -0.098 -0.255" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_4_top">  
      <origin xyz="-0.127 -0.098 -0.135" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_4_bot">  
      <origin xyz="-0.127 -0.098 -0.255" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_5_top">  
      <origin xyz="-0.339 -0.098 -0.135" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_5_bot">  
      <origin xyz="-0.339 -0.098 -0.255" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_6_top">  
      <origin xyz="-0.551 -0.098 -0.135" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_sc_6_bot">  
      <origin xyz="-0.551 -0.098 -0.255" rpy="${-pi/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.001" turns="0.5"/>
      </geometry>
    </collision>
    <collision name="grabbing_mechanism_top">
      <origin xyz="0 0 -0.015" />
      <geometry>
        <box size="1.375 0.26 0.03" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 -1.18 -2.39" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://techtrix_description/meshes/techtrix_grabbing_mechanism.dae" scale="${1/3} ${1/3} ${1/3}" />
      </geometry>
    </visual>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </visual>

    <sensor name="thermal_camera" type="thermal">
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>320</width>
          <height>240</height>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <always_on>1</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <topic>thermal_camera</topic>
    </sensor>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="base_joint" type="prismatic">
    <parent link="world" />
    <child link="frame" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${height/2}" />
    <limit effort="5000.0" lower="0" upper="5.75" velocity="0.5" />
  </joint>

  <joint name="lifting_joint" type="prismatic">
    <parent link="frame" />
    <child link="bearing" />
    <axis xyz="0 0 1" />
    <origin xyz="0 1.5 ${(height/2)-0.125}" />
    <limit effort="6000.0" lower="-1.875" upper="0" velocity="0.25" />
    <dynamics damping="500" friction="20" />
  </joint>

  <joint name="rotating_joint" type="revolute">
    <parent link="bearing" />
    <child link="grabbing_mechanism" />
    <axis xyz="0 0 1" />
    <limit effort="5000.0" lower="${-pi/2}" upper="0" velocity="0.5" />
  </joint>

  <joint name="camera_joint" type="fixed">
    <parent link="frame"/>
    <child link="camera_link"/>
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 1" rpy="0 0 -1.6"/>
  </joint>

  <transmission name="base_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="base_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>20</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="lifting_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lifting_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="lifting_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>20</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rotating_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rotating_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rotating_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo>
    <plugin name="techtrix_grabber_model_plugin" filename="libtechtrix_grabber_model_plugin.so" />
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/techtrix</robotNamespace>
      <robotParam>/techtrix_description</robotParam>
    </plugin>
  </gazebo>
</robot>
