<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="techtrix_robot">
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:property name="pi" value="3.1415926535897931" />
  <xacro:property name="length" value="1.6" />
  <xacro:property name="width" value="1.5" />
  <xacro:property name="height" value="2.3" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <link name="frame">
    <!-- <collision>
      <geometry>
        <box size="${width} ${length} ${height}" />
      </geometry>
    </collision> -->
    <visual>
      <origin xyz="0 0.375 -2.355" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://techtrix_description/meshes/techtrix_frame.dae" scale="${1/3} ${1/3} ${1/3}" />
      </geometry>
    </visual>
    <xacro:default_inertial mass="1"/>
  </link>

  <link name="bearing">
    <xacro:default_inertial mass="1"/>
  </link>

  <link name="grabber">
    <collision>
      <origin xyz="0 0 -0.015" />
      <geometry>
        <box size="1.375 0.26 0.03" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 -1.133 -2.7575" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://techtrix_description/meshes/techtrix_grabber.dae" scale="${1/3} ${1/3} ${1/3}" />
      </geometry>
    </visual>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="base_joint" type="prismatic">
    <parent link="world" />
    <child link="frame" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${height/2}" />
    <limit effort="1000.0" lower="0" upper="5.75" velocity="0.5" />
  </joint>

  <joint name="lifting_joint" type="prismatic">
    <parent link="frame" />
    <child link="bearing" />
    <axis xyz="0 0 1" />
    <origin xyz="0 1.5 ${(height/2)-0.125}" />
    <limit effort="1000.0" lower="-1.475" upper="0" velocity="0.1" />
  </joint>

  <joint name="rotating_joint" type="revolute">
    <parent link="bearing" />
    <child link="grabber" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" lower="${-pi/2}" upper="0" velocity="0.5" />
  </joint>

  <transmission name="base_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="base_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="lifting_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lifting_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="lifting_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rotating_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rotating_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rotating_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/techtrix</robotNamespace>
      <robotParam>/techtrix_description</robotParam>
    </plugin>
  </gazebo>
</robot>
